services:
  - type: web
    name: ratemyshow
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn rateMySh.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ratemyshow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ratemyshow-redis
          property: connectionString
    previewPlanChanges: false

  - type: redis
    name: ratemyshow-redis
    ipAllowList: []
    plan: free
    region: oregon

databases:
  - name: ratemyshow-db
    engine: postgres
    version: "15"
    plan: free
    region: oregon
    databaseName: ratemyshow
    previewPlanChanges: false
