# Generated by Django 4.2.13 on 2026-05-28 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_omdb_ids', models.JSONField(blank=True, default=list)),
                ('similarity_scores', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='similar_titles_cache', to='titles.title')),
            ],
            options={
                'verbose_name_plural': 'Similar Titles',
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('common_ratings', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_to', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('collaborative', 'Users like you watched this'), ('genre', 'Based on your favorite genres'), ('actor', 'Features actors you like'), ('trending', 'Trending this week'), ('similar', 'Similar to movies you rated highly')], max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_based_on', to='titles.title')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-confidence_score'], name='recommendat_user_id_265c98_idx'), models.Index(fields=['user', '-created_at'], name='recommendat_user_id_1f9da7_idx'), models.Index(fields=['-confidence_score'], name='recommendat_confide_5d1643_idx')],
                'unique_together': {('user', 'title', 'reason')},
            },
        ),
        migrations.CreateModel(
            name='CollaborativeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_rating', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', '-updated_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
