# Generated by Django 4.2.13 on 2026-05-28 09:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('born_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omdb_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'TV Series'), ('episode', 'Episode')], max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=20)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('plot', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('imdb_votes', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rating_count', models.IntegerField(default=0)),
                ('director', models.CharField(blank=True, max_length=500)),
                ('writer', models.CharField(blank=True, max_length=500)),
                ('production', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('omdb_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='titles', to='titles.actor')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_titles', to='titles.person')),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='titles.genre')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
                'ordering': ['-imdb_rating', '-rating_count'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('to-watch', 'To Watch'), ('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='to-watch', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='0=Low, 1=Medium, 2=High')),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-added_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='titles_watc_user_id_038c04_idx'), models.Index(fields=['user', '-added_at'], name='titles_watc_user_id_bcd923_idx')],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['omdb_id'], name='titles_titl_omdb_id_6a5ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['title'], name='titles_titl_title_8dbdf9_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['type'], name='titles_titl_type_1f8db4_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-avg_rating'], name='titles_titl_avg_rat_4787a0_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['-rating_count'], name='titles_titl_rating__2af61f_idx'),
        ),
    ]
