# Generated by Django 4.2.13 on 2026-05-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watched_at',
            field=models.DateTimeField(blank=True, help_text='When marked as watched', null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('to-watch', 'To Watch'), ('watching', 'Watching'), ('watched', 'Watched'), ('dropped', 'Dropped')], default='to-watch', max_length=20),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['status'], name='titles_watc_status_9ce32b_idx'),
        ),
    ]
