# Generated by Django 4.2.13 on 2026-05-28 09:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Rating from 1 to 10 (supports 0.5 increments)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_10', models.IntegerField(default=0)),
                ('count_9', models.IntegerField(default=0)),
                ('count_8', models.IntegerField(default=0)),
                ('count_7', models.IntegerField(default=0)),
                ('count_6', models.IntegerField(default=0)),
                ('count_5', models.IntegerField(default=0)),
                ('count_4', models.IntegerField(default=0)),
                ('count_3', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
                ('count_1', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_distribution', to='titles.title')),
            ],
            options={
                'verbose_name_plural': 'Rating Distributions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_review', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('contains_spoilers', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('unhelpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='ratings.rating')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-helpful_count', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ratings_rev_user_id_f31632_idx'), models.Index(fields=['title', '-created_at'], name='ratings_rev_title_i_2c5c7d_idx'), models.Index(fields=['contains_spoilers'], name='ratings_rev_contain_d42f43_idx')],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', '-created_at'], name='ratings_rat_user_id_e6a510_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['title', '-created_at'], name='ratings_rat_title_i_325f15_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['score'], name='ratings_rat_score_5b2efc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'title')},
        ),
    ]
